# Generated by Django 5.1.7 on 2025-04-07 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_sala', models.IntegerField()),
                ('descricao', models.CharField(max_length=255)),
                ('ni', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Gestores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ni', models.IntegerField()),
                ('nome', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='abertura',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='fechamento',
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='data_abertura',
            field=models.DateTimeField(auto_now_add=True, default='2025-04-07 14:38:35'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='data_encerramento',
            field=models.DateTimeField(auto_now_add=True, default='2025-04-07 14:38:35'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='manutentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.manutentores'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='patrimonio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.patrimonios'),
        ),
        migrations.AlterField(
            model_name='manutentores',
            name='ni',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='prioridade',
            field=models.CharField(choices=[('Alta', 'alta'), ('Media', 'media'), ('Baixa', 'baixa')], default='Baixa', max_length=10),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='patrimonios',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='patrimonios',
            name='localizacao',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patrimonios',
            name='ni',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='ambiente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ambientes'),
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_encerramento', models.DateTimeField(auto_now_add=True)),
                ('descricao_manutencao', models.TextField()),
                ('ordem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ordemservico')),
            ],
        ),
        migrations.CreateModel(
            name='Responsaveis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ni', models.IntegerField()),
                ('nome', models.CharField(max_length=100)),
                ('ambiente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ambientes')),
                ('gestor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.gestores')),
            ],
        ),
        migrations.AddField(
            model_name='ambientes',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.responsaveis'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.responsaveis'),
        ),
    ]
