# Generated by Django 5.1.7 on 2025-04-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_patrimonios_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrimonios',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
