# Generated by Django 5.1.7 on 2025-04-14 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_patrimonios_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patrimonios',
            name='nome',
        ),
    ]
